version: "3.8"
services:
  redis:
    image: redis:alpine
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data/redis-data:/data

  linebot:
    image: wayne900619/mr.coding-linebot
    depends_on:
      - redis
    ports:
      - "1225:1225"
